### ISSUE TITLE
pygdf fails py.test

### ISSUE THREAD

**Issue by abeduplaa** [gpuopenanalytics/pygdf#101]
I am re-installing pygdf on a linux ubuntu 16.04 instance with 1 NVIDIA K80 (Driver version 384.111). I started to have a pygdf 'invalid shared memory key' error and decided to reinstall pygdf. I am now trying to re-create an environment from notebook_py35.yml. The steps to remove and re-create the conda environment are shown below:
Steps taken to reinstall:
1. Remove pygdf conda envrionment (conda remove)
2. Did a conda clean to remove all from cache
3. re created pygdf environment
4. activated pygdf environment
5. **Tried to run py.test but got the error 'no module named libgdf_cffi'**

Not sure why the it won't pass py.test anymore.

The downloading of packages while creating pygdf env has no warning or error

**Comment by sklam** [comment]
I did the following and it works:

```bash
conda env create --name pygdf_notebook --file conda_environments/notebook_py35.yml
source activate pygdf_notebook
cd <source-root-of-pygdf>
pytest
```

> Remove pygdf conda envrionment (conda remove)

To remove an environment, use `conda env remove -n <env-name>`.
`conda remove` removes a package from the current environment.

**Comment by abeduplaa** [comment]
I wasn't able to get it to work, but I am now using an older commit with an older pymapd commit and it is now functioning properly

**Comment by sklam** [comment]
@abeduplaa , do you mean you are able to install the packages but the notebooks are not working?

**Comment by kkraus14** [comment]
Closing as seems to be a resolved environment issue.

**Comment by wuxianliang** [comment]
@abeduplaa could cudf 0.2 work with old k80? I wish it can.

**Comment by harrism** [comment]
cuDF uses CUDA Unified Memory, which requires Pascal (Compute Capability 6.0+) or newer GPUs
