### ISSUE TITLE
adding pymapd to conda notebook environment

### ISSUE THREAD

**Issue by abeduplaa** [gpuopenanalytics/pygdf#102]
Would it be possible to add pymapd to notebook_py35.yml? It would take away one step from having to install pymapd after creating the pygdf environment.

**Comment by wamsiv** [comment]
Abe, All cross project demos are available in [gpuopenanalytics/demo-docker](https://github.com/gpuopenanalytics/demo-docker) which includes the [reference to pymapd](https://github.com/gpuopenanalytics/demo-docker/blob/master/notebook-demo-docker/demo/Dockerfile#L38). The reason being this is specific to `pygdf` repo and all example notebooks in this repo are legacy and will be moved in sometime to `demo-docker`.

**Comment by abeduplaa** [comment]
Thanks wamsi!
