### ISSUE TITLE
apply() function using Numba JIT

### ISSUE THREAD

**Issue by seibert** [gpuopenanalytics/pygdf#11]
Support for apply()'ing a function to each row of a GDF.  Will use Numba JIT to generate code.

**Comment by sklam** [comment]
https://github.com/gpuopenanalytics/pygdf/pull/55 implemented `.applymap` using `numba.cuda.jit` for map like operation on Series.

We still need a row-wise apply to satisfy this feature request.

**Comment by kkraus14** [comment]
This is implemented in `apply_rows()`.
