### ISSUE TITLE
Function to append/concat GDFs

### ISSUE THREAD

**Issue by kkraus14** [gpuopenanalytics/pygdf#112]
If you currently want to append GDFs you can create an empty GDF and define each column by appending the columns of the dataframes.

Example:
```
import pandas as pd
from pygdf.dataframe import DataFrame

pdf1 = pd.DataFrame({"col1": [1,2,3], "col2": [11,12,13]})
pdf2 = pd.DataFrame({"col1": [4,5,6], "col2": [14,15,16]})
pdf3 = pd.DataFrame({"col1": [7,8,9], "col2": [17,18,19]})

gdf1 = DataFrame.from_pandas(pdf1)
gdf2 = DataFrame.from_pandas(pdf2)
gdf3 = DataFrame.from_pandas(pdf3)

append_gdfs = [gdf1, gdf2, gdf3]
newgdf = DataFrame()
for col in gdf1.columns:
    new_col = None
    for gdf in append_gdfs:
        if new_col is None:
            new_col = gdf[col]
        else:
            new_col = new_col.append(gdf[col])
    newgdf[col] = new_col
```

There should be append and concat functions similar to pandas.DataFrame.append and pandas.concat for appending dataframe(s).

**Comment by sklam** [comment]
There is already a concat function in https://github.com/gpuopenanalytics/pygdf/blob/master/pygdf/multi.py.
For append, there is a Series.append but we don't have a DataFrame.append yet.

**Comment by kkraus14** [comment]
Closing this and will create a new issues for Series.append.
