### ISSUE TITLE
cannot load library 'libgdf.so'

### ISSUE THREAD

**Issue by bnu-unipus** [gpuopenanalytics/pygdf#117]
wen i use

python setup.py install
python setup.py build

install and build pygdf.

then,run py.test
an OSError exist:

cannot load library 'libgdf.so': libgdf.so: cannot open shared object file: No such file or directory

**Comment by sklam** [comment]
You will need to install https://github.com/gpuopenanalytics/libgdf.
We don't have wheels for libgdf yet, so you must install with `conda`.  i.e. `conda install -c defauls -c conda-forge -c gpuopenanalytics/label/dev libgdf libgdf_cffi`

Or follow the setup instructions at https://github.com/gpuopenanalytics/pygdf#setup-with-conda for easier setup.

**Comment by bnu-unipus** [comment]
thank you very much.
But another error has emerged.
**"AttributeError: cffi library 'libgdf.so' has no function, constant or global variable named 'gdf_left_join_generic' "**

**Comment by bnu-unipus** [comment]
I use 
'''
conda env update --name libgdf_dev --file ../conda_environments/builddocs_py35.yml
'''
solve the above error.

I offer my thanks again
Pygdf willing to get better and better

**Comment by kkraus14** [comment]
This seems to be resolved, closing.
