### ISSUE TITLE
Improve documentation around environment

### ISSUE THREAD

**Issue by randyzwitch** [gpuopenanalytics/pygdf#119]
I think it would be helpful to highlight:

- [ ] Where users are supposed to install pygdf (same computer as MapD running on, inside of a MapD docker image itself, etc.)
- [ ] Which version of CUDA and CUDA tools are necessary

Last night, I tried to install pygdf from a git clone on Pop_OS! (which is mostly Ubuntu 17.10) and got hundreds of test failures when running `py.test` (can provide stack trace if desired). This morning, I tried installing on a DGX-Workstation(Ubuntu 16.04) and only got 3 failed tests.

**Comment by kkraus14** [comment]
@randyzwitch re point #1: pygdf is not dependent on MapD, i.e. you can read a CSV into a Pandas DataFrame and convert that into a pygdf DataFrame without using MapD.

If you're looking to use pygdf + MapD via PyMapD or Thrift directly then you'd want it on the same host in the same IPC namespace as wherever MapD is running. That means running pygdf in the same container, running in a separate container with a shared ipc namespace between the two containers, or running directly on the host and specifying the MapD container's IPC namespace to use the host's IPC namespace.

I believe this documentation should be added to the PyMapD / MapD repos if it doesn't already exist there.

Adding @andrewseidl for visibility and any additional comments.

**Comment by randyzwitch** [comment]
Thanks for the clarification, and sorry for not being more clear...

As I was going through the example notebooks in the pygdf repo, the examples in the README seem to switch contexts implicitly:

`COPY ipums_easy FROM './ipums_easy.csv';`

If I'm using the MapD CE Docker image, the above statement would imply the pygdf directory is inside the Docker container or mounted. However, currently I have pygdf installed outside of the MapD container (but on the same computer), so it took a bit to realize I could move the data file into the MapD container.

So it could just be clearer where a user should install pygdf (per your answer, wherever it can access the GPUs you want to use), and that MapD is completely separate.

**Comment by randyzwitch** [comment]
Couple points of reference, now that I've had success with 100% of `py.test` tests passing, installing just in the conda environment (no Docker containers).

- Ubuntu 16.04.4 LTS (GNU/Linux 4.13.0-37-generic x86_64) (Pop_OS/Ubuntu 17.10 didn't seem to work)
- NVIDIA-SMI 384.111
- CUDA not required to be installed

I'll close this because technically I don't need any more help, but perhaps clarifying the README for these or the actual minimum dependencies would help out the next person to try.

**Comment by datametrician** [comment]
Thanks, @randyzwitch! We will be spending a lot of time updating all the READMEs and adding more testing soon.  Feel free to submit a PR for anything in the meantime.  Also, we really appreciate people using issues, thank you! Please join the slack channel as well.

**Comment by randyzwitch** [comment]
I'll definitely start contributing to README's and documentation once I get acclimated.
