### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by bnu-unipus** [gpuopenanalytics/pygdf#121]
an import error is arised
when i try import pygdf after import h2o4gpu

```
In [1]: import h2o4gpu

In [2]: import pygdf
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-3bac7a01023c> in <module>()
----> 1 import pygdf

~/anaconda3/lib/python3.6/site-packages/pygdf/__init__.py in <module>()
----> 1 from .dataframe import DataFrame
      2 from .series import Series
      3 from .multi import concat
      4 
      5 from .settings import set_options

~/anaconda3/lib/python3.6/site-packages/pygdf/dataframe.py in <module>()
      9 from numba import cuda
     10 
---> 11 from . import cudautils, formatting, queryutils, _gdf, applyutils
     12 from .index import GenericIndex, EmptyIndex, Index, RangeIndex
     13 from .series import Series

~/anaconda3/lib/python3.6/site-packages/pygdf/_gdf.py in <module>()
     10 from numba import cuda
     11 
---> 12 from libgdf_cffi import ffi, libgdf
     13 from . import cudautils
     14 

~/anaconda3/lib/python3.6/site-packages/libgdf_cffi/__init__.py in <module>()
     28             return path
     29 
---> 30     libgdf_api = ffi.dlopen(_get_lib_name())
     31     libgdf = _libgdf_wrapper(ffi, libgdf_api)
     32 

OSError: cannot load library 'libgdf.so': /home/u/anaconda3/lib/python3.6/site-packages/../../libgdf.so: undefined symbol: _ZN5arrow3ipc10JsonWriter6FinishEPSs
```

**Comment by kkraus14** [comment]
Hi @bnu-unipus, how did you install pygdf and h2o4gpu? I just tested and was unable to reproduce your issue through installing pygdf via conda and installing h2o4gpu via the wheel using pip.

**Comment by zfchen95** [comment]
Have you solved the problem? I got the same error

**Comment by kkraus14** [comment]
@zfchen95 How did you install pygdf and h2o4gpu? Could you give me commands to reproduce?

**Comment by zfchen95** [comment]
@kkraus14 Just figured it out. It was about gcc version. I was supposed to set gcc version to 4.8.

**Comment by kkraus14** [comment]
@zfchen95 Thanks! Were you using the conda install commands? If there's any issue where conda isn't pulling the correct gcc version I'll submit a PR to fix it.

**Comment by zfchen95** [comment]
@kkraus14 Not with conda. I was running make pytest on libgdf and saw the same error. Probably would be fine for pygdf?

**Comment by kkraus14** [comment]
@zfchen95 Yea libgdf needs to be built with gcc 4.8 for the Arrow ABI compatibility with the arrow builds pushed to conda-forge, and pygdf depends on libgdf. If that's the case you should be fine, but if you run into any problems just raise an issue.
