### ISSUE TITLE
groupby.count() extremely slow

### ISSUE THREAD

**Issue by robocopnixon** [gpuopenanalytics/pygdf#129]
I recently tried to run the following code:

`
output = new_gdf.groupby(by=['ID','label_field']).count()
`
This has taken several minutes to run before I've ultimately interrupted the function before it completes. The data set is less than a million rows. This is being run on a high end system. For comparison, the same operation in pandas runs in about 24 seconds.

Only about 1.3% of IDs will appear more than once in the final grouping.

**Comment by kkraus14** [comment]
nvprof dump of the code with the above statement:
[paul_test.nvvp.zip](https://github.com/gpuopenanalytics/pygdf/files/1975219/paul_test.nvvp.zip)

**Comment by kkraus14** [comment]
Closing this issue as groupbys have been reworked and there isn't a relevant example for reproduction.
