### ISSUE TITLE
How to generate schema + gpu_data using latest GpuArrowReader

### ISSUE THREAD

**Issue by pseudotensor** [gpuopenanalytics/pygdf#158]
Hi,

We used to have a script that works for pygdf and h2o4gpu, but it no longer works due to a change in pygdf that I'm confused about.  Can I get help?

See:  https://github.com/h2oai/gpuopenai/blob/master/pygdf/notebooks/mapd_to_pygdf_to_matrix_3-smallipums_4matrices.ipynb

I don't see how in this notebook to create some schema needed now by GpuArrowReader.

I might be able to re-write the whole thing, but I'm trying to show something tomorrow.

I can see the changes made here:
https://github.com/gpuopenanalytics/pygdf/commit/50347914a1b230e5d8a420e8f6e285dd1315331e

But it's not obvious how to do this within the mapd-numba-pygdf framework.

**Comment by pseudotensor** [comment]
@sklam

**Comment by pseudotensor** [comment]
I'm basically looking for the minimal change to get this schema.  I think once that's done, the rest should work fine.

**Comment by pseudotensor** [comment]
Somewhat related: https://github.com/mapd/mapd-core/issues/43

**Comment by sklam** [comment]
With the new changes, users can use [pymapd](https://github.com/mapd/pymapd) to get a `pygdf.DataFrame` directly from a MapD query.  See docs about [`pymapd.Connection.select_ipc_gpu`](http://pymapd.readthedocs.io/en/latest/api.html#pymapd.Connection.select_ipc_gpu).

**Comment by pseudotensor** [comment]
I can still get the actual directly copy of a simple data pointer to a contiguous data block like before?
