### ISSUE TITLE
Add tests for categorical data for unique, unique_count, and value_counts 

### ISSUE THREAD

**Issue by kkraus14** [gpuopenanalytics/pygdf#167]
Tests should be added for the fixes merged in #153

**Comment by beckernick** [comment]
@kkraus14 I can pick this up

**Comment by beckernick** [comment]
Sounds great, thanks! @kkraus14 are we able to make branches/PRs directly to this project or should we be exclusively working in forks?

**Comment by kkraus14** [comment]
> Sounds great, thanks! @kkraus14 are we able to make branches/PRs directly to this project or should we be exclusively working in forks?

We've been working exclusively in forks + PRs
