### ISSUE TITLE
TravisCI builds failing due to too many arguments to conda build command

### ISSUE THREAD

**Issue by kkraus14** [gpuopenanalytics/pygdf#168]
Looks like conda build updated and the way we've been passing the arguments no longer works.

LibGDF Issue: https://github.com/gpuopenanalytics/libgdf/issues/78

**Comment by scopatz** [comment]
What do you mean here exactly, @kkraus14?

**Comment by kkraus14** [comment]
If you look at a recent travisci build, for example: https://travis-ci.org/gpuopenanalytics/pygdf/jobs/409058208

They're failing at the end with:
```
./travisci/upload-anaconda.sh: line 10: test: too many arguments
```

That line runs this environment variable: https://github.com/gpuopenanalytics/pygdf/blob/master/travisci/upload-anaconda.sh#L4

So it looks like something changed in conda build that we need to address.

**Comment by kkraus14** [comment]
The conda build command is returning:
```============================================================ Warning: Importing conda-verify failed. Please be sure to test your packages. conda install conda-verify to make this message go away. ============================================================ /home/travis/miniconda3/conda-bld/linux-64/pygdf-0.1.0a2-py36_248.tar.bz2```
instead of just the filename as expected.
