### ISSUE TITLE
Typo in README?

### ISSUE THREAD

**Issue by fvisconti** [gpuopenanalytics/pygdf#17]
You say to 
`conda env create --name pygdf_dev --file conda_environments/testing_py35.yml`, but it seems to produce a conflict (Mac OSX) since in the `name` field in the yaml file there's another string.
Using 
`conda env create  --file conda_environments/testing_py35.yml` just goes fine.

**Comment by sklam** [comment]
The `--name` option is to specify an alternative name.  The name in the yaml file is the default if `--name ...` is not given.  The rest of the readme refer "pygdf_dev".

**Comment by sklam** [comment]
If you see something like `CondaValueError: prefix already exists: /Users/me/miniconda3/envs/pygdf_dev`, it is just that you already have an environment named "pygdf_dev".  You can use any other name you like in `--name <envname>`.
