### ISSUE TITLE
Drop Python 2.7 support 

### ISSUE THREAD

**Issue by kkraus14** [gpuopenanalytics/pygdf#174]
Seeing as numerous other major projects (some of which we depend on) have plans for dropping Python 2.7 support, we should drop Python 2.7 support now while we're still under heavy development and haven't started doing formal releases yet.

If I receive positive feedback (or no feedback) to this issue I'll follow up with a WIP pull request removing the Python 2.7 builds from CI.

**Comment by kkraus14** [comment]
LibGDF issue: https://github.com/gpuopenanalytics/libgdf/issues/81

**Comment by scopatz** [comment]
My hot take on this is that new(er) projects and efforts should not expend the time and energy to add or maintain support Python 2.7. It isn't worth the effort unless there is some specific need or use case. So in general I am in favor of dropping Python 2.7 support.
