### ISSUE TITLE
Conda installation procedure needs to be updated

### ISSUE THREAD

**Issue by rgsl888prabhu** [gpuopenanalytics/pygdf#214]
## Reporting a bug

- [Y] I am using the latest version of PyGDF from conda or built from `master`.
- [Y] I have included the following environment details:
      Linux Distro, Linux Kernel, GPU Model
- [Y] I have included the following version information for:
      Arrow, CUDA, Numpy, Pandas, Python
- [Y] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

This is just regarding the the procedure mentioned for conda installation. The new version has changes in the function name such as "gdf_multi_left_join_generic" to "gdf_left_join" and is not same in the version mentioned in the README.

Please update the README for conda procedure.

**Comment by kkraus14** [comment]
@rgsl888prabhu Thanks for the bug report, I see the issue that the installation instructions in the readme refer to 0.1.0a2 instead of 0.1.0a3. Would you be interested in submitting a pull request with an update? I'd be happy to review and merge it!

**Comment by rgsl888prabhu** [comment]
Hi Keith,
               I have submitted, please review.

**Comment by kkraus14** [comment]
@rgsl888prabhu I'm not seeing the pull request, could you link it here?

**Comment by rgsl888prabhu** [comment]
https://github.com/gpuopenanalytics/pygdf/pull/215

**Comment by kkraus14** [comment]
Fixed by #215.
