### ISSUE TITLE
Rethink class structure

### ISSUE THREAD

**Issue by jcrist** [gpuopenanalytics/pygdf#38]
While working to implement things like `concat`, I've noticed a few (potential) issues with the current design that may bite us in the future. I'll lay them out here. Feel free to ignore, I'm very new to working with this codebase and may be missing reasons for the existing layout.

### Current Structure

- A DataFrame contains:
  - A dictionary of columns to series
  - An index

- A Series contains:
  - A buffer
  - A "mask" representing missingness
  - An implemenation depending on the dtype.

- An index could be many things, but the generic one just wraps a series.

- A numeric implementation contains:
  - A dtype

- A categorical implementation contains:
  - A dtype
  - A codes dtype
  - A numerical implementation for the codes dtype
  - A set of categories
  - Whether the categories have an order

This structure results in a few odd things:

- A DataFrame and each of its series all contain references to the same index. This currently isn't checked, but must be true for correctness.
- The numeric implementation contains no data, but the categorical implementation does. This makes figuring out where to put methods kind of confusing.

### Proposed new structure

- A DataFrame contains:
  - a dictionary of column names to data objects
  - an index

- A series contains:
  - a data object
  - an index

- A data object contains:
  - a dtype
  - a mask
  - all methods for working with that dtype

- An Index is basically the same as before, but contains a data object instead of a series.

This new layout is nicer because:
- A dataframe only has one index reference. A new series is created each time it's indexed out of that dataframe, but this is cheap since it's just a new python object wrapping an existing (not copied) buffer.

```python
def __getitem__(self, key):
    return Series(self._columns[key], index=self.index)
```

- Internally many algorithms are working with data objects instead of series. This makes keeping consistent dtypes, dealing with masks, and extra state from categoricals a lot easier. No longer does the categorical implementation object have to match the data buffer that's passed along inside a series. Correctly implementing `concat` becomes easier, as all necessary state is located on the same object.

**Potential Example Class Hierarchy**

```python
class Data(object):
   pass

class NumericData(Data):
    def __init__(self, buffer, mask, dtype):
        pass

class CategoricalData(Data):
    def __init__(self, codes : NumericData, categories, ordered=False):
        pass

class Series(object):
    def __init__(self, data, index=None):
        pass

class DataFrame(object):
    def __init__(self, cols_and_data, index=None):
        pass
```

I don't *think* rearranging this would be that tricky. It basically amounts to moving the buffer storage into the implementation classes, and fixing existing code as necessary.

**Comment by sklam** [comment]
> A DataFrame and each of its series all contain references to the same index. This currently isn't checked, but must be true for correctness.

It is checked at https://github.com/gpuopenanalytics/pygdf/blob/f3330612316e2f40fb0bda205ee2ad6ad212bc62/pygdf/dataframe.py#L286.  Series' index must be equivalent to the dataframe index..

**Comment by sklam** [comment]
> The numeric implementation contains no data, but the categorical implementation does. This makes figuring out where to put methods kind of confusing.

The categorical impl doesn't contain data.  I think `_categories` and `_ordered` are metadata.

All `SeriesImpl` subclasses do not contain data.  They are the delegates.  When a type-specialized operation is invoked, a Series calls a SeriesImpl to handle the operation.  In SeriesImpl, the methods always take the "calling" series as one of the arguments. 

To add new type-specialized methods, the actual implementation goes to SeriesImpl.  The Series will have a small wrapper to delegate the work.

However, I have been lazy sometimes and the actual implementation is put directly to Series.  That's okay for now.

**Comment by sklam** [comment]
As for the proposed class hierarchy, the only difference I see would be where the data is.  In `SeriesImpl`, the data is always passed as an arg of `Series` type.  Whereas is in the new `Data` class, it will be under `self`.  I would prefer not to couple the data and the type-specialized operation.

**Comment by jcrist** [comment]
> Series' index must be equivalent to the dataframe index..

> The categorical impl doesn't contain data. I think _categories and _ordered are metadata.

Ah, you are correct in both cases. Ignore my gripes there :).

> As for the proposed class hierarchy, the only difference I see would be where the data is. In SeriesImpl, the data is always passed as an arg of Series type. Whereas is in the new Data class, it will be under self. I would prefer not to couple the data and the type-specialized operation.

My only remaining issue is that I'm finding myself frequently using `Series` where an array would suffice. For example, `GenericIndex` is backed by a series (which also has an index). Concat is another example - to avoid repeatedly concatenating the same index arrays I had to do a kludgy hack in #40. With array like objects (that understand categoricals), `concat` could work on the arrays, and then wrap the final output in a series/dataframe with a concatenated index.

I think it would be nice to build operations on a generic data container without an index. Since categorical data has metadata (categories and ordered) at least the categorical data container would have to be a step higher than a gpu array. This is similar to pandas - `pd.Series` are either backed by numpy arrays or `pd.Categorical`.

Again, feel free to ignore, I'm still figuring things out. I think the differences between this project and pandas are tripping me up and that's leading to confusion on my part.

**Comment by sklam** [comment]
I agree that the `GenericIndex` design has issues.  I hacked it up to make progress.  It's backed by a `Series` just because `Series` has a lot of features.  But, the `Series` in `GenericIndex` should always have the basic `RangeIndex` as to not recursively containing more `Series`.

> My only remaining issue is that I'm finding myself frequently using Series where an array would suffice.

That's true.  Sadly, the underlying numba gpu array is not as feature-rich. 

Now, I think it make sense to introduce the `Data` classes.  

So the `Buffer` class will be the physical layer.  The `Data` class will be the logical layer.

**Comment by sklam** [comment]
Closing due to #54
