### ISSUE TITLE
GDF_CUDA_ERROR on binary operation with dataframe columns

### ISSUE THREAD

**Issue by subhankarshah** [gpuopenanalytics/pygdf#59]
Hi,

I am trying to do some basic add and multiply operations on dataframe columns but it is throwing GDF_CUDA_ERROR everytime.

Below is the code and stacktrace.

```
from pygdf.dataframe import DataFrame
import numpy as np

size = 100000000
df = DataFrame([('a', np.random.random(size)),('b', np.random.random(size))])
print('some rows',df.loc[:5])

df['a'] = df['a'] + df['b']

print('some rows',df.loc[:5])
```

Traceback (most recent call last):
  File "test.py", line 9, in <module>
    df['a'] = df['a'] + df['b']
  File "/home/test_proj/pygdf/pygdf/series.py", line 234, in __add__
    return self._binaryop(other, 'add')
  File "/home/test_proj/pygdf/pygdf/series.py", line 221, in _binaryop
    outcol = self._column.binary_operator(fn, other._column)
  File "/home/test_proj/pygdf/pygdf/numerical.py", line 65, in binary_operator
    out_dtype=self.dtype)
  File "/home/test_proj/pygdf/pygdf/numerical.py", line 180, in numeric_column_binop
    null_count = _gdf.apply_binaryop(op, lhs, rhs, out)
  File "/home/test_proj/pygdf/pygdf/_gdf.py", line 68, in apply_binaryop
    binop(*args)
  File "/root/miniconda3/envs/pygdf_dev/lib/python3.5/site-packages/libgdf_cffi/wrapper.py", line 28, in wrap
    raise GDFError(errcode, errname)
libgdf_cffi.wrapper.GDFError: GDF_CUDA_ERROR

**Comment by randerzander** [comment]
This issue has resurfaced on my GeForce GT 710. While I'm sure libgdf's primary focus is not such low-end cards, is there a config or change I can make to get a custom build working on this type of card?

**Comment by datametrician** [comment]
Do you experience this problem on a GTX 10 series? Just trying to determine if it's only a 7 series issue.

**Comment by shwina** [comment]
I had the same issue on a Tesla K40c (using Docker, CUDA 8.0). I found that this is related to https://github.com/gpuopenanalytics/libgdf/issues/72.

The above script and many tests were failing.

As a workaround, I rebuilt libgdf with ``arch=compute_35,code=sm_35`` in https://github.com/gpuopenanalytics/libgdf/blob/master/CMakeLists.txt#L82

**Comment by avloss** [comment]
same issue with Tesla K80

**Comment by mt-jones** [comment]
As mentioned in

https://github.com/gpuopenanalytics/libgdf/issues/72

libgdf assumes a Volta architecture. Similarly, there are unguarded features in the library that require Pascal architecture at minimum. 

This means certain codes just break or cause a crash on Maxwell/Kepler.

**Comment by randerzander** [comment]
Thanks @shwina and @mt-jones for the info.

While it doesn't help resolve [libgdf #72](https://github.com/gpuopenanalytics/libgdf/issues/72), I created a workaround for the PyGDF Dockerfile [here](https://github.com/randerzander/pygdf/tree/libgdf_issue_72). It may be helpful for others experimenting with these projects in the meantime.

**Comment by kkraus14** [comment]
Closing as this is a build issue and not a binary operation issue.
