### ISSUE TITLE
Use pyarrow to generate test data for Arrow IPC reads 

### ISSUE THREAD

**Issue by wesm** [gpuopenanalytics/pygdf#64]
The tests in https://github.com/gpuopenanalytics/pygdf/blob/master/pygdf/tests/test_gpu_arrow_parser.py use hard-coded binary data. This makes it more difficult to programmatically extend these tests. 

I opened https://issues.apache.org/jira/browse/ARROW-1406 to ensure that this is easy to do and documented. So you will be able to obtain a memoryview containing the serialized schema and record batch in the form that you have currently.

**Comment by sklam** [comment]
I'm adding some notes about the hardcoded binary data.  

The existing hardcoded data are generated from mapd via pymapd's `select_ipc_gpu`.  The related source line in mapd are:
* schema writing: https://github.com/mapd/mapd-core/blob/fae2f9079fb3fa1f60200212443adaac752e3030/QueryEngine/ResultSetConversion.cpp#L418
* recordbatch writing: https://github.com/mapd/mapd-core/blob/fae2f9079fb3fa1f60200212443adaac752e3030/QueryEngine/ResultSetConversion.cpp#L458

Moving all the gpu serialization logic into arrow will allow us to simplify the tests here in pygdf, and to make it easier for all GOAI projects to implement the same serialization format.

**Comment by wesm** [comment]
Sounds good. We are setting up nightly builds of pyarrow (using the conda-forge toolchain for builds) so that if you require a new function in between conda-forge releases (which are loosely tied to Apache releases) you aren't affected by that. I'll first try to reproduce the existing test case but using dynamically generated IPC messages. We should be able to remove the Flatbuffers files from libgdf also

cc @cpcloud

**Comment by kkraus14** [comment]
Fixed by #200
