### ISSUE TITLE
Mentioning Apache Arrow in the README

### ISSUE THREAD

**Issue by wesm** [gpuopenanalytics/pygdf#84]
While there's no obligation to do so, it would be positive for the OSS community to mention that Arrow is an important component of how the GDF works. 

For example, I have had people ask me about this article https://devblogs.nvidia.com/parallelforall/goai-open-gpu-accelerated-data-analytics/, and the lines

```
from pygdf.gpuarrow import GpuArrowReader
reader = GpuArrowReader(darr)
```

e.g. "is that the same Arrow?". It's mentioned nowhere in that article. In the blog post it says "Without shared GPU data structures provided by GOAI". This is a little bit misleading. It would be good to acknowledge that this isn't all an endogenous creation and there is a broader community at work on these problems (zero-copy columnar data interchange).

**Comment by datametrician** [comment]
Agreed. We’re going through and making updates across the board.

**Comment by kkraus14** [comment]
Apache Arrow is now mentioned and linked off to in the README. Thanks!
