### ISSUE TITLE
Installer: ResolvePackageNotFound

### ISSUE THREAD

**Issue by lmeyerov** [gpuopenanalytics/pygdf#89]
I just did a fresh `conda` install (OS X) and tried to install `pygdf`, but hit  `ResolvePackageNotFound` on `libgdf`. Pointers / any recommendations on things to try / report back? 

Thanks!

```
Leos-MBP:pygdf lmeyerov$ conda --version
conda 4.3.30
Leos-MBP:pygdf lmeyerov$ conda env create --name pygdf_dev --file conda_environments/testing_py35.yml
Fetching package metadata .................

ResolvePackageNotFound: 
  - libgdf 0.1.0a2.dev hb999fd6_2
```

**Comment by lmeyerov** [comment]
Maybe related: this laptop can do OpenCL, not CUDA, and it looks like pygdf relies on cuda-only @cuda.jit. If so, maybe a dependencies/env req section on the README , or even a smarter installer somehow, is the real issue.

**Comment by sklam** [comment]
@lmeyerov , you will need a CUDA-enabled GPU to use pygdf/libgdf.  But the reason for the package not found is due to lack of package.  Currently, there are automatic builders for linux packages only.  I am building and uploading the OSX packages manually but I have not done so for the latest one.

**Comment by kkraus14** [comment]
Closing as this is resolved.
