### ISSUE TITLE
Install Error: symbol not found in library libgdf.so

### ISSUE THREAD

**Issue by gwulfs** [gpuopenanalytics/pygdf#95]
Getting the following error when I try import pygdf. Appreciative of any and all guidance!

error: symbol 'gdf_left_join_generic' not found in library 'libgdf.so': /home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/../../libgdf.so: undefined symbol: gdf_left_join_generic

**Comment by bnu-unipus** [comment]
hi, i have the same error. how did u solve it??

**Comment by ingenieroariel** [comment]
I ran into the same problem today.

**Comment by wamsiv** [comment]
@ingenieroariel How are you installing `pygdf`?
